# `.\pytorch\.github\scripts\test_tryrebase.py`

```py
from typing import Any
from unittest import main, mock, TestCase

from gitutils import get_git_remote_name, get_git_repo_dir, GitRepo
from test_trymerge import mocked_gh_graphql
from trymerge import GitHubPR
from tryrebase import additional_rebase_failure_info, rebase_ghstack_onto, rebase_onto


def mocked_rev_parse(branch: str) -> str:
    return branch


MAIN_BRANCH = "refs/remotes/origin/main"
VIABLE_STRICT_BRANCH = "refs/remotes/origin/viable/strict"


class TestRebase(TestCase):
    @mock.patch("trymerge.gh_graphql", side_effect=mocked_gh_graphql)
    @mock.patch("gitutils.GitRepo._run_git")
    @mock.patch("gitutils.GitRepo.rev_parse", side_effect=mocked_rev_parse)
    @mock.patch("tryrebase.gh_post_comment")
    def test_rebase(
        self,
        mocked_post_comment: Any,
        mocked_rp: Any,
        mocked_run_git: Any,
        mocked_gql: Any,
    ) -> None:
        "Tests rebase successfully"
        # 创建 GitHubPR 对象，代表 GitHub 上的一个 Pull Request
        pr = GitHubPR("pytorch", "pytorch", 31093)
        # 创建 GitRepo 对象，代表当前的 Git 仓库
        repo = GitRepo(get_git_repo_dir(), get_git_remote_name())
        # 执行 rebase 操作到主分支（MAIN_BRANCH）
        rebase_onto(pr, repo, MAIN_BRANCH)
        # 预期的 Git 命令调用列表
        calls = [
            mock.call("fetch", "origin", "pull/31093/head:pull/31093/head"),
            mock.call("rebase", MAIN_BRANCH, "pull/31093/head"),
            mock.call(
                "push",
                "-f",
                "https://github.com/mingxiaoh/pytorch.git",
                "pull/31093/head:master",
            ),
        ]
        # 断言 Git 命令是否按预期调用
        mocked_run_git.assert_has_calls(calls)
        # 断言成功重基的评论是否包含预期内容
        self.assertIn(
            f"Successfully rebased `master` onto `{MAIN_BRANCH}`",
            mocked_post_comment.call_args[0][3],
        )

    @mock.patch("trymerge.gh_graphql", side_effect=mocked_gh_graphql)
    @mock.patch("gitutils.GitRepo._run_git")
    @mock.patch("gitutils.GitRepo.rev_parse", side_effect=mocked_rev_parse)
    @mock.patch("tryrebase.gh_post_comment")
    def test_rebase_to_stable(
        self,
        mocked_post_comment: Any,
        mocked_rp: Any,
        mocked_run_git: Any,
        mocked_gql: Any,
    ) -> None:
        "Tests rebase to viable/strict successfully"
        # 创建 GitHubPR 对象，代表 GitHub 上的一个 Pull Request
        pr = GitHubPR("pytorch", "pytorch", 31093)
        # 创建 GitRepo 对象，代表当前的 Git 仓库
        repo = GitRepo(get_git_repo_dir(), get_git_remote_name())
        # 执行重基操作到稳定分支（VIABLE_STRICT_BRANCH）
        rebase_onto(pr, repo, VIABLE_STRICT_BRANCH, False)
        # 预期的 Git 命令调用列表
        calls = [
            mock.call("fetch", "origin", "pull/31093/head:pull/31093/head"),
            mock.call("rebase", VIABLE_STRICT_BRANCH, "pull/31093/head"),
            mock.call(
                "push",
                "-f",
                "https://github.com/mingxiaoh/pytorch.git",
                "pull/31093/head:master",
            ),
        ]
        # 断言 Git 命令是否按预期调用
        mocked_run_git.assert_has_calls(calls)
        # 断言成功重基的评论是否包含预期内容
        self.assertIn(
            f"Successfully rebased `master` onto `{VIABLE_STRICT_BRANCH}`",
            mocked_post_comment.call_args[0][3],
        )

    @mock.patch("trymerge.gh_graphql", side_effect=mocked_gh_graphql)
    @mock.patch("gitutils.GitRepo._run_git", return_value="Everything up-to-date")
    @mock.patch("gitutils.GitRepo.rev_parse", side_effect=mocked_rev_parse)
    # 使用模拟的 mocked_rev_parse 替换 GitRepo.rev_parse 方法
    @mock.patch("tryrebase.gh_post_comment")
    # 使用模拟的 gh_post_comment 替换 tryrebase.gh_post_comment 方法
    def test_no_need_to_rebase(
        self,
        mocked_post_comment: Any,
        mocked_rp: Any,
        mocked_run_git: Any,
        mocked_gql: Any,
    ) -> None:
        "Tests branch already up to date"
        # 创建 GitHubPR 对象，表示 pytorch 项目的 PR #31093
        pr = GitHubPR("pytorch", "pytorch", 31093)
        # 获取当前 Git 仓库的目录和远程名称，创建 GitRepo 对象
        repo = GitRepo(get_git_repo_dir(), get_git_remote_name())
        # 尝试在 repo 上对 PR 进行重新基于 MAIN_BRANCH 的 rebase 操作
        rebase_onto(pr, repo, MAIN_BRANCH)
        # 预期的 Git 命令调用序列
        calls = [
            mock.call("fetch", "origin", "pull/31093/head:pull/31093/head"),
            mock.call("rebase", MAIN_BRANCH, "pull/31093/head"),
            mock.call(
                "push",
                "-f",
                "https://github.com/mingxiaoh/pytorch.git",
                "pull/31093/head:master",
            ),
        ]
        # 断言 mocked_run_git 方法被按照 calls 序列调用
        mocked_run_git.assert_has_calls(calls)
        # 断言在调用 mocked_post_comment 方法时，包含指定的提示信息
        self.assertIn(
            "Tried to rebase and push PR #31093, but it was already up to date",
            mocked_post_comment.call_args[0][3],
        )
        # 断言在调用 mocked_post_comment 方法时，不包含指定的提示信息
        self.assertNotIn(
            "Try rebasing against [main]",
            mocked_post_comment.call_args[0][3],
        )

    @mock.patch("trymerge.gh_graphql", side_effect=mocked_gh_graphql)
    # 使用模拟的 mocked_gh_graphql 替换 trymerge.gh_graphql 方法
    @mock.patch("gitutils.GitRepo._run_git", return_value="Everything up-to-date")
    # 使用模拟的 _run_git 方法，返回字符串 "Everything up-to-date"
    @mock.patch("gitutils.GitRepo.rev_parse", side_effect=mocked_rev_parse)
    # 使用模拟的 mocked_rev_parse 替换 GitRepo.rev_parse 方法
    @mock.patch("tryrebase.gh_post_comment")
    # 使用模拟的 gh_post_comment 替换 tryrebase.gh_post_comment 方法
    def test_no_need_to_rebase_try_main(
        self,
        mocked_post_comment: Any,
        mocked_rp: Any,
        mocked_run_git: Any,
        mocked_gql: Any,
    ) -> None:
        "Tests branch already up to date again viable/strict"
        # 创建 GitHubPR 对象，表示 pytorch 项目的 PR #31093
        pr = GitHubPR("pytorch", "pytorch", 31093)
        # 获取当前 Git 仓库的目录和远程名称，创建 GitRepo 对象
        repo = GitRepo(get_git_repo_dir(), get_git_remote_name())
        # 尝试在 repo 上对 PR 进行重新基于 VIABLE_STRICT_BRANCH 的 rebase 操作
        rebase_onto(pr, repo, VIABLE_STRICT_BRANCH)
        # 断言在调用 mocked_post_comment 方法时，包含指定的提示信息
        self.assertIn(
            "Tried to rebase and push PR #31093, but it was already up to date. Try rebasing against [main]",
            mocked_post_comment.call_args[0][3],
        )

    @mock.patch("trymerge.gh_graphql", side_effect=mocked_gh_graphql)
    # 使用模拟的 mocked_gh_graphql 替换 trymerge.gh_graphql 方法
    @mock.patch("gitutils.GitRepo._run_git")
    # 使用模拟的 _run_git 方法
    @mock.patch("gitutils.GitRepo.rev_parse", side_effect=lambda branch: "same sha")
    # 使用 lambda 函数模拟的 rev_parse 方法，总是返回字符串 "same sha"
    @mock.patch("tryrebase.gh_post_comment")
    # 使用模拟的 gh_post_comment 替换 tryrebase.gh_post_comment 方法
    def test_same_sha(
        self,
        mocked_post_comment: Any,
        mocked_rp: Any,
        mocked_run_git: Any,
        mocked_gql: Any,
    ) -> None:
        "Tests rebase results in same sha"
        # 创建 GitHubPR 对象，表示 pytorch 项目的 PR #31093
        pr = GitHubPR("pytorch", "pytorch", 31093)
        # 获取当前 Git 仓库的目录和远程名称，创建 GitRepo 对象
        repo = GitRepo(get_git_repo_dir(), get_git_remote_name())
        # 使用 rebase_onto 方法尝试在 repo 上对 PR 进行重新基于 MAIN_BRANCH 的 rebase 操作，
        # 预期会抛出异常，异常信息包含 "same sha as the target branch"
        with self.assertRaisesRegex(Exception, "same sha as the target branch"):
            rebase_onto(pr, repo, MAIN_BRANCH)
        # 使用 rebase_ghstack_onto 方法尝试在 repo 上对 PR 进行重新基于 MAIN_BRANCH 的 rebase 操作，
        # 预期会抛出异常，异常信息包含 "same sha as the target branch"
        with self.assertRaisesRegex(Exception, "same sha as the target branch"):
            rebase_ghstack_onto(pr, repo, MAIN_BRANCH)
    # 定义一个测试方法，用于测试额外的重基信息函数的行为
    def test_additional_rebase_failure_info(self) -> None:
        # 构造包含错误信息的字符串，模拟 Git 命令返回非零退出码的情况
        error = (
            "Command `git -C /Users/csl/zzzzzzzz/pytorch push --dry-run -f "
            "https://github.com/Lightning-Sandbox/pytorch.git pull/106089/head:fix/spaces` returned non-zero exit code 128\n"
            "```\n"
            "remote: Permission to Lightning-Sandbox/pytorch.git denied to clee2000.\n"
            "fatal: unable to access 'https://github.com/Lightning-Sandbox/pytorch.git/': The requested URL returned error: 403\n"
            "```py"
        )
        # 调用 additional_rebase_failure_info 函数，传入构造的异常信息字符串，并获取返回的额外重基信息
        additional_msg = additional_rebase_failure_info(Exception(error))
        # 断言返回的额外信息中包含指定的错误提示语句
        self.assertTrue("This is likely because" in additional_msg)
# 如果当前模块被直接执行（而不是被导入到其他模块中执行），那么执行以下代码块
if __name__ == "__main__":
    # 调用主函数 main()
    main()
```